# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCfX-EUN1fUETPCjY7vJCNINMiNKbxyI
"""


import streamlit as st
import pandas as pd

def load_data(uploaded_file):
    return pd.read_excel(uploaded_file)

def main():
    st.title("Meat Description Classifier")

    uploaded_file = st.file_uploader("Upload your Excel file", type=["xlsx"], key="meat_uploader")

    if uploaded_file is not None:
        df = load_data(uploaded_file)
        st.write("File Preview:")
        st.write(df.head())

        # Your prediction logic goes here
        description_input = st.text_input("Enter product description to predict:")
        if description_input:
            prediction = predict_description(description_input, df)
            st.success(f"Predicted Consolidated nan descript: {prediction}")

def predict_description(input_text, df):
    input_text = input_text.lower()

    exclude_keywords = df["Exclude Retailer description"].dropna().unique()
    consolidated_keywords = df["Consolidated nan descript"].dropna().unique()

    for keyword in exclude_keywords:
        if keyword.lower() in input_text:
            return "Excluded due to retailer keyword"

    for desc in consolidated_keywords:
        if any(word in input_text for word in desc.lower().split()):
            return desc

    return "No matching Consolidated nan descript found"

if __name__ == "__main__":
    main()

